---
swagger: "2.0"
info:
  title: "Service Toggles"
  description: "A REST API for toggling features in company services"
  version: "1.0.0"
consumes:
- application/json
produces:
- application/json

securityDefinitions:
  # username and password
  BasicAuth:
    type: basic
  JWT:
    type: apiKey
    in: header
    name: X-API-Key
definitions:
  Config:
    type: object
    properties:
      toggles:
        type: object
        additionalProperties:
          type: array
          items:
            $ref: '#/definitions/ConfigNode'
    example:
      toggles:
        isButtonBlue:
          allow_all: true
          value: true
          unless:
            deny_all: true
            allow:
              - name: ABC
                value: false
        isButtonGreen:
          deny_all: true
          allow:
            - name: ABC
              value: false
        isButtonRed:
          allow_all: true
          deny:
            - name: ABC
  ConfigNode:
    type: object
    properties:
      deny_all:
        type: boolean
      allow_all:
        type: boolean
      allow:
        type: array
        items:
          $ref: '#/definitions/Service'
      deny:
        type: array
        items:
          $ref: '#/definitions/Service'
      value:
        type: boolean
      unless:
        type: array
        items:
          $ref: '#/definitions/ConfigNode'
    example:
      isButtonBlue:
        allow_all: true
        value: true
        unless:
          deny_all: true
          allow:
            - name: ABC
              value: false
  Service:
    type: object
    required:
      - name
      - value
    properties:
      name:
        type: string
      version:
        type: string
      value:
        type: boolean