---
swagger: "2.0"
info:
  title: "Service Toggles"
  description: "A REST API for toggling features in company services"
  version: "1.0.0"
consumes:
- application/json
produces:
- application/json

securityDefinitions:
  # username and password
  basicAuth:
    type: basic
  # X-API-Key: abcdef12345
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key