---
swagger: "2.0"
info:
  title: "API"
  description: "REST API"
  version: "1.0.0"
consumes:
- application/json
produces:
- application/json

securityDefinitions:
  # username and password
  basicAuth:
    type: basic
  # X-API-Key: abcdef12345
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
  # /path?api_key=abcdef12345
  APIKeyQueryParam:
    type: apiKey
    in: query
    name: api_key